language: java
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "baraneetharan-github"
    token:
      secure: 5440b0e65f5d7649a722d23996224976f5b68c46

before_install:
  - chmod +x mvnw
script: "mvn test && mvn verify && mvn package sonar:sonar"

# script:
# - ./mvnw clean install -B
# - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

notifications:
    slack: docket-workspace:wLFGj3Bp0Wdsb5qw82bYuqoO